global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8001']
  - job_name: 'streamlit'
    static_configs:
      - targets: ['streamlit:8501']